apiVersion: v1
kind: Service
metadata:
  name: rest-redis-clusterip-service
  labels:
    app: service-rest-redis
spec:
  selector:
    app: service-rest-redis
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080