apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-config
build:
  cluster:
    namespace: local-jenkins-namespace
  artifacts:
    - image: cp22590/service-rest-redis
#      docker:
#        dockerfile: Dockerfile
      kaniko:
        dockerfile: Dockerfile
#        buildArgs:
#          localDir: {}
  tagPolicy:
    sha256: {}